### ISSUE TITLE
[1.1.1] Server drops players on join

### ISSUE THREAD

**Issue by noncom** [VentureCraftMods/MC-Gliders#37]
Hi!
Updating from 1.1.0 from 02-07-2023 to 1.1.0 from 11-07-2023 or 1.1.1 from 11-07-2023 causes joining players to be immediately dropped from the server.

Attaching the server log, the error is right near the end of it: 
[latest.log](https://github.com/VentureCraftMods/MC-Gliders/files/12036559/latest.log)

Also FYI there's some strange versions confusion in CF. Idk if anything can be (needs to be?) done about it, but here's what it looks like:
<img width="880" alt="image" src="https://github.com/VentureCraftMods/MC-Gliders/assets/2920144/1aa904d2-070e-4564-bd30-66cf705e7cf6">

**Comment by whatamaniac** [comment]
Helloo, I'm facing the same issue i guess on my server with the latest version of mod. Not being able to join the server. Here are the logs: `[Server thread/INFO]: WhataManiac joined the game
[13.07 14:41:02] [Server] [Server thread/INFO]: [STDOUT]: [Progressive Bosses] Player WhataManiac spawned a Wither. Difficulty: 0
[13.07 14:41:02] [Server] [Server thread/INFO]: Async chunk loading for player WhataManiac completed
[13.07 14:41:02] [Server] [Server thread/WARN]: §b[Neruina]: §cCaught Ticking Player, WhataManiac has been kicked.
[13.07 14:41:02] [Server] net.minecraft.util.crash.CrashExceptionTicking player
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:551) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayNetworkHandler.mixinextras$bridge$0$method_14226(ServerPlayNetworkHandler.java) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayNetworkHandler.wrapOperation$dpg000$neruina$tick(ServerPlayNetworkHandler.java:10021) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:268) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:248) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:183) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:886) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.MinecraftServer.handler$bda000$carpet$modifiedRunLoop(MinecraftServer.java:6885) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?]
[13.07 14:41:02] [Server] Caused byjava.lang.NoClassDefFoundError: net/minecraft/ClientPlayerEntity
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.data.GliderData.glideAndFallLogic(GliderData.java:60) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.data.GliderData.tick(GliderData.java:36) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.common.GliderEvents.lambda$livingEntityTick$0(GliderEvents.java:86) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.common.GliderEvents.livingEntityTick(GliderEvents.java:86) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.threetag.palladiumcore.event.LivingEntityEvents.lambda$static$9(LivingEntityEvents.java:33) ~[palladiumcore-1.19.2-1.4.1.1-e78335c0a1f7625.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.LivingEntity.handler$ecj00a$palladiumcore$tick(LivingEntity.java:31734) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:284) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:487) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	... more
[13.07 14:41:02] [Server] Caused byjava.lang.ClassNotFoundException: net.minecraft.client.network.ClientPlayerEntity
[13.07 14:41:02] [Server] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
[13.07 14:41:02] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[13.07 14:41:02] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
[13.07 14:41:02] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
[13.07 14:41:02] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.data.GliderData.glideAndFallLogic(GliderData.java:60) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.data.GliderData.tick(GliderData.java:36) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.common.GliderEvents.lambda$livingEntityTick$0(GliderEvents.java:86) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
[13.07 14:41:02] [Server] 	at net.venturecraft.gliders.common.GliderEvents.livingEntityTick(GliderEvents.java:86) ~[vc_gliders-fabric-1.1.1.jar:?]
[13.07 14:41:02] [Server] 	at net.threetag.palladiumcore.event.LivingEntityEvents.lambda$static$9(LivingEntityEvents.java:33) ~[palladiumcore-1.19.2-1.4.1.1-e78335c0a1f7625.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.LivingEntity.handler$ecj00a$palladiumcore$tick(LivingEntity.java:31734) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:284) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:487) ~[server-intermediary.jar:?]
[13.07 14:41:02] [Server] 	... more
[13.07 14:41:02] [Server] [pool-10-thread-1/INFO]: §b[Neruina]: §cCaught Ticking Player, WhataManiac has been kicked.
[13.07 14:41:02] [Server] [Server thread/INFO]: Received secret request of WhataManiac (17)
[13.07 14:41:02] [Server] [Server thread/INFO]: Sent secret to WhataManiac
[13.07 14:41:02] [Disconnect] WhataManiac has disconnected, reason§b[Neruina]: §cYou have been kicked due to a ticking exception on the player. Please remove the culprit mod or contact an admin.
[13.07 14:41:02] [Server] [Server thread/INFO]: WhataManiac left the game`

**Comment by MoTao233** [comment]
same

**Comment by Suff99** [comment]
Hey guys, looks like a easy fix - I’ll get it out tonight, if not as soon as possible

**Comment by Suff99** [comment]
https://modrinth.com/mod/gliders/version/1.1.2+forge
https://modrinth.com/mod/gliders/version/1.1.2+fabric
